/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DevMonitor;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Yaye
 */
public class Home extends javax.swing.JFrame {

    private static int userType; 
    
    //constants for the various user types
    public static final int USERTYPE_ChiefAdministrator = 1;
    public static final int USERTYPE_Admin = 2;
    public static final int USERTYPE_Teacher = 3;
    public Home() {
        initComponents();
         this.setLocationRelativeTo(null);//to center the frame
         userType = LogIn.user.getUserType(); //assign the user's type
        
        if (userType == USERTYPE_Admin) 
        {
            //if the user is not an a chief administrator disable the 'Administrator' button
            btnAdmins.setEnabled(false);
        }
        //if the user is a teacher, disable Device,Students and Administrator buttons
        else if(userType != USERTYPE_Admin && userType != USERTYPE_ChiefAdministrator){
            btnDevices.setEnabled(false);         
            btnAdmins.setEnabled(false);
            btnStudents.setEnabled(false);
        }      
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHead = new javax.swing.JPanel();
        txtUserOutput = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnDevices = new javax.swing.JButton();
        btnStudents = new javax.swing.JButton();
        btnAdmins = new javax.swing.JButton();
        btnLendDevice = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        lblSelect = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlHead.setBackground(new java.awt.Color(0, 0, 102));
        pnlHead.setForeground(new java.awt.Color(0, 0, 102));
        pnlHead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserOutput.setFont(new java.awt.Font("Tribeca", 0, 24)); // NOI18N
        txtUserOutput.setForeground(new java.awt.Color(255, 255, 51));
        txtUserOutput.setText("Welcome to device monitor");
        pnlHead.add(txtUserOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 16, 498, 62));

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/help.png"))); // NOI18N
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        pnlHead.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 43, 34));

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setForeground(new java.awt.Color(102, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDevices.setBackground(new java.awt.Color(0, 0, 51));
        btnDevices.setFont(new java.awt.Font("Virgo 01", 0, 12)); // NOI18N
        btnDevices.setForeground(new java.awt.Color(255, 255, 0));
        btnDevices.setText("Manage Devices");
        btnDevices.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDevices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevicesActionPerformed(evt);
            }
        });
        jPanel1.add(btnDevices, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 173, 79));

        btnStudents.setBackground(new java.awt.Color(0, 0, 51));
        btnStudents.setFont(new java.awt.Font("Virgo 01", 0, 12)); // NOI18N
        btnStudents.setForeground(new java.awt.Color(255, 255, 0));
        btnStudents.setText("Manage Students");
        btnStudents.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 387, 173, 79));

        btnAdmins.setBackground(new java.awt.Color(0, 0, 51));
        btnAdmins.setFont(new java.awt.Font("Virgo 01", 0, 12)); // NOI18N
        btnAdmins.setForeground(new java.awt.Color(255, 255, 0));
        btnAdmins.setText("Manage Administrators");
        btnAdmins.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminsActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 173, 79));

        btnLendDevice.setBackground(new java.awt.Color(0, 0, 51));
        btnLendDevice.setFont(new java.awt.Font("Virgo 01", 0, 12)); // NOI18N
        btnLendDevice.setForeground(new java.awt.Color(255, 255, 0));
        btnLendDevice.setText("Lend a device");
        btnLendDevice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLendDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLendDeviceActionPerformed(evt);
            }
        });
        jPanel1.add(btnLendDevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 167, 173, 79));

        btnReturn.setBackground(new java.awt.Color(0, 0, 51));
        btnReturn.setFont(new java.awt.Font("Virgo 01", 0, 12)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 0));
        btnReturn.setText("Return Device");
        btnReturn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 61, 173, 79));

        btnHistory.setBackground(new java.awt.Color(0, 0, 51));
        btnHistory.setFont(new java.awt.Font("Virgo 01", 0, 12)); // NOI18N
        btnHistory.setForeground(new java.awt.Color(255, 255, 0));
        btnHistory.setText("Borrowing History");
        btnHistory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 167, 173, 79));

        lblSelect.setFont(new java.awt.Font("Hero", 0, 18)); // NOI18N
        lblSelect.setForeground(new java.awt.Color(0, 153, 153));
        lblSelect.setText("Please select from the options below");
        jPanel1.add(lblSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 31, 385, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("* Chief Admin Only");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 180, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("* Admin/Chief Admin Only");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 472, 180, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("* Admin/Chief Admin Only");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 367, 180, -1));

        pnlHead.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 910, 510));

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        pnlHead.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, -1, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 51));
        lblName.setText("Username");
        pnlHead.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    private void btnAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminsActionPerformed
        // This opens the Administrators GUI
       Administrators admin = new Administrators (); 
       admin.setVisible(true);
       this.setVisible(false);        
    }//GEN-LAST:event_btnAdminsActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        Return r = new Return();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        Borrowings b = new Borrowings();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnDevicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevicesActionPerformed
       //leades to the Devices GUI
       Devices devices = new Devices (); 
       devices.setVisible(true);
               this.setVisible(false);        
    }//GEN-LAST:event_btnDevicesActionPerformed

    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
       Students student = new Students();
       student.setVisible(true);
       this.setVisible(false);
        
       
    }//GEN-LAST:event_btnStudentsActionPerformed

    private void btnLendDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLendDeviceActionPerformed
        Lend lend = new Lend();
        lend.setVisible(true);
        this.setVisible(false);
     
    }//GEN-LAST:event_btnLendDeviceActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        JOptionPane.showMessageDialog(null,"Chose what you would like out of the the supplied options");
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // Log out of account
        LogIn Login = new LogIn ();
        Login.setVisible(true); //Goes back to home
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     //Display name
    lblName.setText(LogIn.user.getAdminName());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmins;
    private javax.swing.JButton btnDevices;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnLendDevice;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSelect;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JLabel txtUserOutput;
    // End of variables declaration//GEN-END:variables
}
