/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DevMonitor;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yaye
 */
public class Lend extends javax.swing.JFrame {

   
   
    public Lend() {
        
        initComponents();
        this.setLocationRelativeTo(null);//to center the frame 
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDevicess = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblLender = new javax.swing.JLabel();
        btnLend = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblLenderuname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        txtRemarks = new javax.swing.JTextField();
        lblDeviceID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnHelp4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Virgo 01", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Lend a device");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 11, 205, 36));

        jLabel2.setFont(new java.awt.Font("Titillium Lt", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select the device you would like to lend ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 53, 446, 25));

        tblDevicess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDevicess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDevicessMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDevicess);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 690, 316));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DeviceID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 50, -1));

        lblLender.setForeground(new java.awt.Color(255, 255, 255));
        lblLender.setText("Lender:");
        jPanel1.add(lblLender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 60, 24));

        btnLend.setText("Lend");
        btnLend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLendActionPerformed(evt);
            }
        });
        jPanel1.add(btnLend, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 436, 109, 32));

        btnBack.setText("<<Back<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 486, 109, 32));

        lblLenderuname.setFont(new java.awt.Font("TGL0-17", 1, 14)); // NOI18N
        lblLenderuname.setForeground(new java.awt.Color(255, 255, 0));
        lblLenderuname.setText("Username");
        jPanel1.add(lblLenderuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 102, 24));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("StudentID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 60, 20));

        txtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 110, -1));

        txtRemarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRemarksActionPerformed(evt);
            }
        });
        jPanel1.add(txtRemarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 330, -1));

        lblDeviceID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDeviceID.setForeground(new java.awt.Color(255, 255, 51));
        lblDeviceID.setText("...");
        jPanel1.add(lblDeviceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 50, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Describe device conditions(any remarks)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 330, -1));

        btnHelp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/help.png"))); // NOI18N
        btnHelp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelp4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnHelp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            LogIn.dbman.Display(tblDevicess, "SELECT DeviceID, DeviceName, DeviceType FROM tblDevice WHERE OutOfUse = false");
        } catch (SQLException ex) {
            Logger.getLogger(Lend.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         lblLenderuname.setText(String.valueOf((LogIn.user.getAdminName())));
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void tblDevicessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDevicessMouseClicked
       int row =tblDevicess.getSelectedRow();
       String  DevID =  tblDevicess.getModel().getValueAt(row,0).toString(); 
       lblDeviceID.setText(DevID);
       

    }//GEN-LAST:event_tblDevicessMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);

        Home home = new Home ();
        home.setVisible(true); //Goes back to home
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void txtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIDActionPerformed
       
    }//GEN-LAST:event_txtStudentIDActionPerformed

    private void txtRemarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRemarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRemarksActionPerformed

    private void btnLendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLendActionPerformed
      if("".equals(txtStudentID.getText()) || "...".equals(lblDeviceID.getText())){
         JOptionPane.showMessageDialog(null, "Please select a record enter a vaild student ID");
     }
      else {
     int DevID =  Integer.parseInt(lblDeviceID.getText());
     int StudID = Integer.parseInt( txtStudentID.getText());     
        try {
            LogIn.dbman.Lend(DevID, StudID, false, LogIn.user.getAdminID(), txtRemarks.getText()); 
            LogIn.dbman.DevStatus(DevID, true); 
            JOptionPane.showMessageDialog(null,"Device Lent successfully" );
        } catch (SQLException ex) {
            Logger.getLogger(Lend.class.getName()).log(Level.SEVERE, null, ex);
        } 
      }
    }//GEN-LAST:event_btnLendActionPerformed

    private void btnHelp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelp4ActionPerformed
        JOptionPane.showMessageDialog(null,"Here you can Lend a device. Simply select the device in the table, enter student's ID \n"
                + "and type any remarks you have and press Lend. \n"
                + "Note: Students should know their ID, the learner should use this when Borrowing a Device");
    }//GEN-LAST:event_btnHelp4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHelp4;
    private javax.swing.JButton btnLend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDeviceID;
    private javax.swing.JLabel lblLender;
    private javax.swing.JLabel lblLenderuname;
    private javax.swing.JTable tblDevicess;
    private javax.swing.JTextField txtRemarks;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables
}
